FROM node:24-trixie-slim AS build

USER node
WORKDIR /app

COPY --chown=node:node . .

RUN yarn install

RUN yarn workspace app build

FROM nginx:1-alpine3.23

COPY --from=build /app/packages/app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
