apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      containers:
        - name: backstage
          image: timotheeren/backstage:sha-204a70157076893522a8f1dc422a3a3fa72e70f2
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_URI
              valueFrom:
                secretKeyRef:
                  name: backstage-postgres-cluster-app
                  key: uri
            - name: BACKEND_HOST
              value: "localhost:8080"
