apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image: timotheeren/kubepods-ui:sha-3f81a471e606b7860b8fdd611c326829a9dbc974
          ports:
            - containerPort: 3000
          env:
            - name: API_HOST
              value: "http://api:3001"
