apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage-frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage-frontend
  template:
    metadata:
      labels:
        app: backstage-frontend
    spec:
      containers:
        - name: backstage-frontend
          image: timotheeren/backstage-frontend:sha-4a7323dcea9d72939373b2c14699de0943d1968f
          ports:
            - containerPort: 80
