apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage-frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage-frontend
  template:
    metadata:
      labels:
        app: backstage-frontend
    spec:
      containers:
        - name: backstage-frontend
          image: timotheeren/backstage-frontend:sha-7265a035fef71d55a868ae036420d6b6b0a99f51
          ports:
            - containerPort: 80
          env:
            - name: BACKEND_HOST
              value: "localhost:7000"
