apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kube-prometheus-stack.yaml
  - cnpg.yaml
  - ingress-traefik.yaml
  - desktops-namespace.yaml
  - grafana-loki.yaml
  - grafana-alloy.yaml
