apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: backstage-postgres-cluster
  namespace: default
spec:
  instances: 1
  bootstrap:
    initdb:
      database: backstage
      owner: app
      postInitSQL:
        - ALTER ROLE app CREATEDB
  storage:
    size: 1Gi
