apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage-backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage-backend
  template:
    metadata:
      labels:
        app: backstage-backend
    spec:
      containers:
        - name: backstage-backend
          image: timotheeren/backstage-backend:sha-8e3643c882f3744b2fae01a5fba7909df222d52d
          ports:
            - containerPort: 7000
          env:
            - name: POSTGRES_URI
              valueFrom:
                secretKeyRef:
                  name: backstage-postgres-cluster-app
                  key: uri
            - name: BACKEND_HOST
              value: "localhost:8080"
