apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage-backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage-backend
  template:
    metadata:
      labels:
        app: backstage-backend
    spec:
      containers:
        - name: backstage-backend
          image: timotheeren/backstage-backend:sha-ab3c53b95f03b7079167554477dd954a6bd5dd30
          ports:
            - containerPort: 7000
          env:
            - name: POSTGRES_URI
              valueFrom:
                secretKeyRef:
                  name: backstage-postgres-cluster-app
                  key: uri
