apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage-backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage-backend
  template:
    metadata:
      labels:
        app: backstage-backend
    spec:
      containers:
        - name: backstage-backend
          image: timotheeren/backstage-backend:sha-2d47caa1320af03e3165c6ba17670794750487a0
          ports:
            - containerPort: 7000
          env:
            - name: POSTGRES_URI
              valueFrom:
                secretKeyRef:
                  name: backstage-postgres-cluster-app
                  key: uri
