name: Backstage CI/CD

on:
  push:
    paths:
      - "backstage/**" # To sync with additional extension config
  workflow_dispatch:

jobs:
  ci:
    uses: timotheeren/backstage-portal/.github/workflows/ci.yml@main
    with:
      image: "backstage"
      path: "Dockerfile"
    secrets:
      dockerhub-username: ${{ vars.DOCKERHUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}

  cd:
    needs: ci
    uses: timotheeren/backstage-portal/.github/workflows/cd.yml@main
    with:
      image: "timotheeren/backstage"
      tag: "sha-${{ github.sha }}"
      path: "backstage"
    secrets:
      token: ${{ secrets.PAT }}
