name: CI

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
    secrets:
      dockerhub-username:
        required: true
      dockerhub-token:
        required: true

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
        with:
          path: .

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf
        with:
          images: ${{ secrets.dockerhub-username }}/${{ inputs.image }}
          tags: |
            type=ref, event=branch
            type=sha, format=long, prefix=sha-

      - name: Log in to DockerHub
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121
        with:
          username: ${{ secrets.dockerhub-username }}
          password: ${{ secrets.dockerhub-token }}

      - name: Build and push
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f
        with:
          context: backstage
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
